server:
  port: 8080

spring:
  data:
    mongodb:
      uri: [MongoURI]

twitter:
  consumer:
    key: [TwitterKey]
    secret: [TwitterSecret]
  access:
    token: [TwitterAccessToken]
    secret: [TwitterAccessSecret]
    
kafka:
  host: localhost
  port: 9092
  tweetTopic: baylorboard.tweets.topic